### PR TITLE
Adds cache invalidation on class.update_counters

### PR DESCRIPTION
**Pull request by jnormore**
Invalidate cache on update_counters class method. This method takes an array of ids so we fetch and expire cache for each.

@dylanahsmith @tjoyal can you take a look please, thanks!

cc @ViSovari @disaacs

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@jnormore can we delete this branch?

**Comment by camilo** [comment]
I deleted it but meh branches are cheap

**Comment by rafaelfranca** [comment]
I asked more because I was looking if there are any work worth to continue.

**Comment by camilo** [comment]
Oh I see we can restore if that is the case, but since it is abandoned I think this might not be needed anymore

**Pull request closed without merging**
