### PR TITLE
add regression test

### PR DESCRIPTION
**Pull request by midu**
follow up to #204, I believe #199 fixed the issue, but here's a regression test

### CODE REVIEW

**Comment by camilo** [comment]
thanks :+1:

**Comment by midu** [comment]
Thank you @camilo, @tjoyal, @dylanahsmith, and @RobWu! Really happy to see this fixed!

Any chance to see a release soon? Doesn't seem like 0.2.4 includes #199

**Comment by dylanahsmith** [comment]
We have pull #199 in production at Shopify, so yes, a release early next week would be appropriate.

**Comment by midu** [comment]
great to hear, thanks!

**Comment by dylanahsmith** [comment]
0.2.5 has been released

**Comment by midu** [comment]
great new, thank you @dylanahsmith!

**Pull request merged**
