### PR TITLE
[WIP] Implement Dalli cache fetcher

### PR DESCRIPTION
**Pull request by maximebedard**
@fbogsany Currently a huge WIP, but any feedback is appreciated 😄

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Any reason why using dali cache store? Active Support memcache store uses Dalli as a client and have better compatibility with Rails.

**Comment by rafaelfranca** [comment]
We can definitely upstream cas support, if dalli has support and our custom store also does it may be useful for everyone

**Comment by maximebedard** [comment]
The problem I have with merge this upstream is that it's not a interface that works for all of the Cache::Store. Which somewhat defeats the purpose of the interface a little bit?

**Comment by rafaelfranca** [comment]
There is no idea of interface. Yes, there is a super class but not every adapter needs to implement all the same features. For example, the file and memory adapter don't have the `_muilti` methods. The documentation of the `Store` super class even mention that each implementation can have specific features https://github.com/rails/rails/blob/8d4e0ab33d5aa4ad46bc648a0636aa788df828cb/activesupport/lib/active_support/cache.rb#L115-L116

**Comment by maximebedard** [comment]
Cool thanks for the feedback, TIL. I'll make sure everything works here and in core, then open a PR in rails to add support for cas/cas_multi and document them appropriately.

**Comment by maximebedard** [comment]
Going to close this one and try to open a PR upstream shortly.

**Pull request closed without merging**
